[package]
name = "rmodbus-tokio-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmodbus = "0.6.1"
lazy_static = "*"
tokio = { version = "0.2.9", features = ["full", "time", "tcp"] }
