connection_configs:
  - protocol_type: "tcp"
    connection:
      host: "127.0.0.1"
      port: "5500"
    channel_id: 1
  - protocol_type: "udp"
    connection:
      host: "127.0.0.1"
      port: "5001"
      listen_host: "127.0.0.1"
      listen_port: "5002"
    channel_id: 2
  - protocol_type: "rtu"
    connection:
      name: "/dev/ttyUSB1"
      baud_rate: 115200
      data_bits: 8
      flow_control: "none"
      parity: "none"
      stop_bits: 1
    channel_id: 3
parameters:
  - name: "switch1"
    unit_id: 1
    ptype: "bool"
    start_address: 0
    mstorage: "DO"
    channel_id: 1
  - name: "switch1"
    unit_id: 1
    ptype: "bool"
    start_address: 1
    mstorage: "DO"
    channel_id: 1
  - name: "switch3"
    unit_id: 1
    ptype: "bool"
    start_address: 8
    mstorage: "DO"
    channel_id: 1

  - name: "door1"
    unit_id: 1
    ptype: "bool"
    start_address: 0
    mstorage: "DI"
    channel_id: 1
  - name: "door2"
    unit_id: 1
    ptype: "bool"
    start_address: 1
    mstorage: "DI"
    channel_id: 1
  - name: "door3"
    unit_id: 1
    ptype: "bool"
    start_address: 7
    mstorage: "DI"
    channel_id: 1

  - name: "speed1"
    unit_id: 1
    ptype: "float"
    start_address: 0
    mstorage: "AO"
    channel_id: 1
  - name: "speed2"
    unit_id: 1
    ptype: "float"
    start_address: 1
    mstorage: "AO"
    channel_id: 1
  - name: "speed3"
    unit_id: 1
    ptype: "float"
    start_address: 4
    mstorage: "AO"
    channel_id: 1

  - name: "temp1"
    unit_id: 1
    ptype: "float"
    start_address: 0
    mstorage: "AI"
    channel_id: 1
  - name: "temp2"
    unit_id: 1
    ptype: "float"
    start_address: 1
    mstorage: "AI"
    channel_id: 1
  - name: "temp3"
    unit_id: 1
    ptype: "float"
    start_address: 5
    mstorage: "AI"
    channel_id: 1
  - name: "temp4"
    unit_id: 1
    ptype: "float"
    start_address: 6
    mstorage: "AI"
    channel_id: 1
